services:
  frontend:
    build:
      context: ./frontend
      target: dev-stage
    ports:
      - "5173:5173"
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - backend
    command: ["npm", "run", "dev"]

  auth-service:
    build: ./services/auth-service
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - backend

  product-service:
    build: ./services/product-service
    ports:
      - "3000:3000"
    env_file:
      - .env

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - backend

networks:
  backend:
    driver: bridge
